apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sources.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - fluent-bit.yaml
  - tempo.yaml
  - opentelemetry-operator.yaml
